package splitwise;

import java.awt.Color;
import java.sql.Timestamp;

public class EditBill extends javax.swing.JFrame {

    // class variables
    int bill_id;
    int user_id;
    Bill thisBill;
    //constructors
    
    public EditBill(int bill_id, int user_id)
    {
        // this will load all the UI Elements/ Swing Components
        initComponents();
        this.bill_id = bill_id;
        this.user_id = user_id;
        api a = new api();
        thisBill = a.getBill(bill_id);
        // Init all the UI Labels
        this.BillName.setText(thisBill.getBillName());
        this.Description.setText(thisBill.getDescription());
        this.Calender.setDate(thisBill.getDate());
        a.closeConnection();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackButton = new javax.swing.JButton();
        Calender = new com.toedter.calendar.JCalendar();
        Date = new javax.swing.JLabel();
        ErrorProvider = new javax.swing.JLabel();
        WelcomeHeader = new javax.swing.JLabel();
        DescLabel = new javax.swing.JLabel();
        BillName = new javax.swing.JTextField();
        NameLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Description = new javax.swing.JTextArea();
        UpdateButton = new javax.swing.JButton();
        EditItemsButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(360, 600));

        BackButton.setText("Back");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        Date.setText("Date");

        ErrorProvider.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ErrorProvider.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        WelcomeHeader.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        WelcomeHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        WelcomeHeader.setText("Edit Bill Form");
        WelcomeHeader.setPreferredSize(new java.awt.Dimension(105, 50));

        DescLabel.setText("Description");

        NameLabel.setText("Name");

        Description.setColumns(20);
        Description.setRows(5);
        jScrollPane1.setViewportView(Description);

        UpdateButton.setText("Update Bill");
        UpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateButtonActionPerformed(evt);
            }
        });

        EditItemsButton.setText("Edit Items");
        EditItemsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditItemsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ErrorProvider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(DescLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(NameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(52, 52, 52))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Date, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Calender, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BillName)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(WelcomeHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(UpdateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BackButton)
                                .addGap(18, 18, 18)
                                .addComponent(EditItemsButton)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(WelcomeHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ErrorProvider, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BillName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DescLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Calender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Date, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UpdateButton)
                    .addComponent(BackButton)
                    .addComponent(EditItemsButton))
                .addContainerGap(93, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Event handler for Back
    // This function will be called when the "Back" Button is clicked.
    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new ShowCreatedBills(user_id).setVisible(true);
    }//GEN-LAST:event_BackButtonActionPerformed

    // Event handler for Update
    // This function will be called when the "Update" Button is clicked.
    private void UpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateButtonActionPerformed
        //        // TODO add your handling code here:
        api a = new api();
        int res;
        res = a.updateBill(this.bill_id, BillName.getText(), Description.getText(), user_id, new Timestamp(Calender.getCalendar().getTimeInMillis()));
        if(res == -1)
        {
            ErrorProvider.setVisible(true);
            ErrorProvider.setForeground(Color.RED);
            ErrorProvider.setText("Bill Creation Error");
        }
        else if(res == -2)
        {
            ErrorProvider.setVisible(true);
            ErrorProvider.setForeground(Color.RED);
            ErrorProvider.setText("Name Can't be Blank");
        }
        else
        {
            this.setVisible(false);
            new ShowCreatedBills(this.user_id).setVisible(true);
        }
        //System.out.println(new Timestamp(Calender.getCalendar().getTimeInMillis()).toString());
    }//GEN-LAST:event_UpdateButtonActionPerformed

    // Event handler for Edit
    // This function will be called when the "Edit" Button is clicked.
    private void EditItemsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditItemsButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new EditBillItems(this.bill_id).setVisible(true);
    }//GEN-LAST:event_EditItemsButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JTextField BillName;
    private com.toedter.calendar.JCalendar Calender;
    private javax.swing.JLabel Date;
    private javax.swing.JLabel DescLabel;
    private javax.swing.JTextArea Description;
    private javax.swing.JButton EditItemsButton;
    private javax.swing.JLabel ErrorProvider;
    private javax.swing.JLabel NameLabel;
    private javax.swing.JButton UpdateButton;
    private javax.swing.JLabel WelcomeHeader;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
