package splitwise;

import java.util.*;

public class ShowBills extends javax.swing.JFrame {

    // Local Variables.
    int user_id;
    List<Bill> createdBills;
    List<Bill> participatedBills;
    // Components
    public ShowBills(int user_id) 
    {
        // This will init all the UI Elements
        initComponents();
        this.user_id = user_id;
        api a = new api();
        WelcomeBanner.setText("All Bills for "+a.getUserName(user_id));
        MessageBox.setVisible(false);
        createdBills = a.getCreatedBills(this.user_id);
        participatedBills = a.getParticipatedBills(this.user_id);
        System.out.println(createdBills.size());
        if(createdBills == null)
                ShowCreatedBillsButton.setEnabled(false);
        else
        {
             if(createdBills.size() <= 0)
                 ShowCreatedBillsButton.setEnabled(false);
            else
                 ShowCreatedBillsButton.setEnabled(true);
        }
        if(participatedBills == null)
            ShowParticipatedBillsButton.setEnabled(false);
        else
        {
            if(participatedBills.size() <= 0)
                 ShowParticipatedBillsButton.setEnabled(false);
            else
                ShowParticipatedBillsButton.setEnabled(true);
        }
        a.closeConnection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MessageBox = new javax.swing.JLabel();
        WelcomeBanner = new javax.swing.JLabel();
        ShowCreatedBillsButton = new javax.swing.JButton();
        ShowParticipatedBillsButton = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(450, 520));

        MessageBox.setForeground(new java.awt.Color(255, 0, 0));
        MessageBox.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        WelcomeBanner.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        WelcomeBanner.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        ShowCreatedBillsButton.setText("Show Created Bills");
        ShowCreatedBillsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowCreatedBillsButtonActionPerformed(evt);
            }
        });

        ShowParticipatedBillsButton.setText("Show Participated Bills");
        ShowParticipatedBillsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowParticipatedBillsButtonActionPerformed(evt);
            }
        });

        BackButton.setText("Back");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(WelcomeBanner, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
                    .addComponent(MessageBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(37, 37, 37))
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BackButton)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ShowCreatedBillsButton)
                        .addGap(56, 56, 56)
                        .addComponent(ShowParticipatedBillsButton)))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(WelcomeBanner, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(MessageBox, javax.swing.GroupLayout.DEFAULT_SIZE, 16, Short.MAX_VALUE)
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ShowCreatedBillsButton)
                    .addComponent(ShowParticipatedBillsButton))
                .addGap(35, 35, 35)
                .addComponent(BackButton)
                .addGap(282, 282, 282))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Event handler for Back
    // This function will be called when the "Back" Button is clicked.
    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new UserHomepage(this.user_id).setVisible(true);
    }//GEN-LAST:event_BackButtonActionPerformed

    // Event handler for ShowParticipatedBills
    // This function will be called when the "Show Participated Bills" Button is clicked.
    private void ShowParticipatedBillsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowParticipatedBillsButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new ShowMyBills(this.user_id).setVisible(true);
    }//GEN-LAST:event_ShowParticipatedBillsButtonActionPerformed

    // Event handler for ShowCreatedBills
    // This function will be called when the "Show Created Bills" Button is clicked.
    private void ShowCreatedBillsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowCreatedBillsButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new ShowCreatedBills(this.user_id).setVisible(true);
    }//GEN-LAST:event_ShowCreatedBillsButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JLabel MessageBox;
    private javax.swing.JButton ShowCreatedBillsButton;
    private javax.swing.JButton ShowParticipatedBillsButton;
    private javax.swing.JLabel WelcomeBanner;
    // End of variables declaration//GEN-END:variables
}
